services:

  db:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure:5
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./sqlfiles:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    tmpfs:
      - /var/run/mysqld
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--port", "3306"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - app_network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
