# J'ai name le Dockerfile.api puisque j'ai gardé le Dockerfile pour le MySQL du TP du matin
FROM python:3.12-slim


LABEL maintainer="Ynov" \
      description="API FastAPI pour le projet Ynov CI"

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN adduser --disabled-password --gecos "" appuser

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .

RUN chown -R appuser:appuser /app

USER appuser

EXPOSE 8000

CMD ["uvicorn", "main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000"]
